internalName: sju

locales:
  en:
    name: &bundleName "Ume Sami Keyboards"
    description: "Keyboards for the Ume Sami language from the Divvun group at UiT."
  nb:
    name: "Umesamisk tastatur"
    description: "Tastatur for umesamisk fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts:
  - sju-mob
  - sju-mac
  - sju-win

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.sju
    icon: images/sju-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.sju
    bundleName: *bundleName
    icon: images/sju-icon.png

  osx:
    <<: *AppleID
    icon: images/sju-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "A4968A00-7685-49F4-9C82-7CDA5BFDCA15"
